"""This module keeps the functions for sequences extraction from MBS files."""

import calendar
import datetime
import multiprocessing as mp
import os
from multiprocessing import Manager

import numpy as np
import pandas as pd
from sklearn.datasets.base import Bunch
from tqdm import tqdm


def get_raw_data(mbs_files, sample_pin_lookout, source):
    """Extract the sequences and find the additional features.

    This function, given the input list of patient identifiers `source` scans
    the `mbs_files` and extract the MBS items sequence. It also finds additional
    info on the patient such as age and sex from the `sample_pin_lookout` file.
    Unstructured sequences and additional info are referred to as raw_data.

    Parameters:
    --------------
    mbs_files: list
        List of input MBS files.

    sample_pin_lookout: string
        Location of the `SAMPLE_PIN_LOOKUP.csv` file.

    source: string
        Location of the 'PTNT_ID' csv file generated by `labels_assignment.py`.

    Returns:
    --------------
    raw_data: dictionary
        A dictionary that stores raw unstructured sequences and additional info
        of each input subject. Each value in the dictionary is a
        `sklearn.datasets.base.Bunch` object.
    """
    raw_data = dict()

    # Step 0: load the source file
    dfs = pd.read_csv(source, header=0)

    # Step 1: get sex and age
    df_pin_lookout = pd.read_csv(sample_pin_lookout, header=0, index_col=0)
    print(df_pin_lookout.head())
    current_year = datetime.datetime.now().year


    print(dfs.head())

    return dict()
